name: scraping
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - selenium
  - pandas
  - matplotlib
  - seaborn
  - numpy
  - scipy
  - scikit-learn
  - jupyter
  - beautifulsoup4
  - requests
  - sqlite
  - django
